kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: oc-start-s2i
spec:
  workspaces:
    - name: build-workspace
      description: Build workspace.
  params:
    - name: APP_NAME
      type: string
  steps:
    - name: run-commands
      image: quay.io/openshift/origin-cli:latest
      workingDir: $(workspaces.build-workspace.path)
      script: |
        #!/usr/bin/env bash
        echo "Workspace includes:"
        ls -la .
        echo "List target contents:"
        ls -l $(workspaces.build-workspace.path)/target
        oc start-build $(params.APP_NAME)-s2i-build --from-file=$(workspaces.build-workspace.path)/target/app.jar -n cicd --follow