kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: print
spec:
  workspaces:
    - name: build-workspace
      description: Build workspace.
  steps:
    - name: echo
      image: maven:3.3.9-jdk-8
      workingDir: $(workspaces.build-workspace.path)
      script: |
          #!/usr/bin/env bash
          echo "workspace target"
          ls -la /workspace/source/target
