apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: petclinic-release-run-
spec:
  pipelineRef:
    name: maven-release
  workspaces:
    - name: build-workspace
      persistentVolumeClaim:
        claimName: release-workspace-pvc
    - name: local-maven-repo
      persistentVolumeClaim:
        claimName: maven-m2-repo-pvc
