kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: petclinic-run-
spec:
  pipelineRef:
    name: maven-build
  workspaces:
    - name: build-workspace
      persistentVolumeClaim:
        claimName: build-workspace-pvc
    - name: local-maven-repo
      persistentVolumeClaim:
        claimName: maven-m2-repo-pvc
