apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd
bases:
- github.com/redhat-canada-gitops/catalog/nexus2/base?ref=master
- github.com/redhat-canada-gitops/catalog/sonarqube8/overlays/plugins?ref=master
resources:
- namespace.yaml
- nexus-secret.yaml
- build-imagestream.yaml
- build-s2i-build.yaml
- image-pullers.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: maven-settings-cm
  files:
  - settings.xml
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: system:image-puller
  path: image-pullers-patch.yaml
