apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: petclinic-template
spec:
  params:
    - name: git-repo-url
      description: The git repository url
    - name: git-repo-revision
      description: The git revision
      default: master
    - name: git-repo-name
      description: The name of the deployment to be created / patched
  resourcetemplates:
    - kind: PipelineRun
      apiVersion: tekton.dev/v1beta1
      metadata:
        name: build-$(params.git-repo-name)-$(uid)
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: maven-build
        params:
          - name: git-repo-url
            value: $(params.git-repo-url)
          - name: git-repo-revision
            value: $(params.git-repo-revision)
        workspaces:
          - name: build-workspace
            persistentVolumeClaim:
              claimName: build-workspace-pvc
          - name: local-maven-repo
            persistentVolumeClaim:
              claimName: maven-m2-repo-pvc
