apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: petclinic-template
spec:
  params:
    - name: git-url
      description: The git repository url
    - name: git-revision
      description: The git revision
      default: master
    - name: git-name
      description: The name of the deployment to be created / patched
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: build-deploy-$(params.git-repo-name)-$(uid)
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: maven-build
        params:
          - name: git-url
            value: $(params.git-url)
          - name: git-revision
            value: $(params.git-revision)
        workspaces:
          - name: build-workspace
            persistentVolumeClaim:
              claimName: build-workspace-pvc
          - name: local-maven-repo
            persistentVolumeClaim:
              claimName: maven-m2-repo-pvc
